name: fogosmobile
description: Fogos.pt new iOS and Android app

version: 3.0.4+30004

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  redux: ^3.0.0
  flutter_redux: ^0.5.2
  redux_logging: ^0.3.0
  flutter_map: ^0.5.0
  http: ^0.12.0
  font_awesome_flutter: ^8.4.0
  firebase_messaging: ^2.1.0
  shared_preferences: ^0.4.3
  diacritic: ^0.1.1
  url_launcher: ^5.0.2

  share: ^0.6.1+1

  #ui
  flutter_svg: ^0.12.4
  modal_progress_hud: ^0.1.3

  #localizations
  intl: ^0.15.7
  intl_translation: ^0.17.4


dev_dependencies:
  build_runner: ^1.2.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/icons/
  - assets/partners/